name: Deploy to Elastic Beanstalk (Docker)

# Trigger the workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Pull your latest code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (required for EB CLI)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install the Elastic Beanstalk CLI (EB CLI)
      - name: Install EB CLI
        run: |
          pip install --upgrade pip
          pip install awsebcli

      # Step 4: Configure AWS credentials from GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5: Initialize, select environment, and deploy
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init ${{ secrets.APP_NAME }} --platform "Docker" --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.ENV_NAME }}
          eb deploy
